title: rin导航
description: 发现优秀的ACGN站点
keywords: 导航, ACGN, Galgame
logo: assets/image/logo/logo.png
assets:
  image:
    path: ./assets/image/
web-item:
  logo:
    path: ./assets/image/logo/


exclude:
  - README.md
  - CNAME
  - kanjian.la.gemspec
  - LICENSE.txt
  - Gemfile
  - Gemfile.lock
  - assets/remixicon/full
  - assets/remixicon/partly/remixicon-collecton.remixicon
