title: 看见导航
description: 看见导航 | 美好的事物，值得被更多人看见
keywords: 导航, 看见导航, 精品网站
logo: assets/image/favicon.png
web-item:
  logo:
    path: ./assets/image/logo/

analystic:
  google:
    gtag: G-WTLLDD0ERC

exclude:
  - README.md
  - CNAME
  - kanjian.la.gemspec
  - LICENSE.txt
  - Gemfile
  - Gemfile.lock
  - assets/remixicon/full
  - assets/remixicon/partly/remixicon-collecton.remixicon
